CREATE TABLE `redirects` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`short_path` VARCHAR(255) UNIQUE NOT NULL,
	`destination_url` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `redirect_reports` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`redirect_id` INT NOT NULL,
	`ip_address` VARCHAR(255),
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);